# Generated by Django 5.0.6 on 2025-03-04 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CertifiedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=20)),
                ('kilometers', models.IntegerField()),
                ('transmission', models.CharField(max_length=20)),
                ('condition', models.TextField()),
                ('reg_number', models.CharField(max_length=20, unique=True)),
                ('insurance_validity', models.DateField()),
                ('pollution_validity', models.DateField()),
                ('tax_validity', models.DateField()),
                ('car_type', models.CharField(max_length=50)),
                ('owner_status', models.IntegerField()),
                ('car_cc', models.IntegerField()),
                ('car_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'reg_number')},
            },
        ),
        migrations.CreateModel(
            name='CertifiedCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certified_car_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certified_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Users.certifiedcar')),
            ],
        ),
    ]
