# Generated by Django 5.0.6 on 2025-03-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_chatmessage_image_alter_chatmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
    ]
